[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xfab387"
index = 16

[[colors.indexed_colors]]
color = "0xf5e0dc"
index = 17

[colors.bright]
black = "0x585b70"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xa6adc8"
yellow = "0xf9e2af"

[colors.cursor]
cursor = "0xf5e0dc"
text = "0x1e1e2e"

[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xbac2de"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/run/current-system/sw/bin/tmux"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true

[terminal]
